# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy API Azure Function

on:
  push:
    branches:
      - vNext
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "api/FilterLists.Api"
  DOTNET_VERSION: "6"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: |
          dotnet build ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} -c Release -o ./output --no-self-contained -r win-x86 -p:PublishReadyToRun=true

      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: func-filterlistsapi-prod-eastus2
          slot-name: Production
          package: ./output
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_07FA9737E3E4421590FEEE5334235CED }}
